server:
  port: 8395

spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: ""
  h2:
    console:
      enable: true
      path: "/h2"
  devtools:
    livereload:
      enabled: true

logging:
  level:
    root: "info"
    org.springframework: "info"
